version: "3.7"

services:
  mysql:
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
      - 3306:3306
    volumes:
      - ./docker/mysql:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: eduplatform
      MYSQL_USER: abc
      MYSQL_PASSWORD: root
    networks:
      - default

  phpmyadmin:
    image: phpmyadmin
    restart: always
    ports:
      - 8081:80
    environment:
      - PMA_ARBITRARY=10
      - PMA_HOST=mysql
      - PMA_USER=root
      - PMA_PASSWORD=root
      - PMA_PORT=3306
    depends_on:
      - mysql
    networks:
      - default

  redis:
    image: redis:5-alpine
    container_name: doodle_redis
    volumes:
      - ./docker/redis:/data
    ports:
      - 6379:6379
    restart: unless-stopped
    environment:
      - REDIS_URL= redis:6379
    networks:
      - default

networks:
  default:
    driver: bridge
